### PR TITLE
Python Language added

### PR DESCRIPTION
**Pull request by senthilnathan-dev**
# Python language

I've added the _'Hello, world!'_ script to the python directory. kindly check out and add to your repo @GabrielTheophilo .

### CODE REVIEW

**Comment by GabrielTheophilo** [comment]
Already checked it out and its Ok

**Review by GabrielTheophilo — APPROVED** [review]
HelloWorld in Python is OK and the name of the merge should be changed to "Create Python.py"
Also, my files that have been already merged should be deleted to avoid changing the title of the commit on the repository

**Review by g1f1 — APPROVED** [review]
Is OK 👍

**Comment by g1f1** [comment]
Thanks for your contributions 💯

**Pull request merged**
